const en = {
  "O NAMA": "ABOUT US",
  "SADRŽAJI": "CONTENTS",
  "APARTMAN": "APARTMENT",
  "NAPOMENA": "REMARK",
  "GALERIJA": "GALLERY",
  "CIJENE": "PRICES",
  "Novo renovirani apartman (3*) u samom centru Osijeka": "Newly renovated apartment (3*) in the very center of Osijek",
  "Neposredna blizina kulturno-obrazovnih ustanova, znamenitosti, parkova i raznih zabavnih sadržaja garantira vam da ćete iskusiti srce Slavonije u punom sjaju": "The close proximity of cultural and educational institutions, city landmarks, parks and a number of entertainment contents guarantee that you will experience the hear of Slavonia in it's fullest glory",
  "Apartman je veličine 146m2 i prikladan je za 4 do 6 osoba": "The apartment is 146m2 in size and appropriate for 4 to 6 people",
  "Sastoji se od kuhinje, blagavaonice i dnevnog boravka spojenih u jednom prostoru, 3 spavaće sobe, 2 kupaonice, hodnika, spremišta, balkona i ostakljene terase ( prostor za pušenje )": "It consists of a kitchen, dining room and living room as a single area, 3 bedrooms, 2 bathrooms, a balcony and a glass-lined terrace (smoking area) ",
  "Cijeli prostor je klimatiziran": "The entire space is air-conditioned",
  "Unutar zgrade nema trajnih stanovnika, tako da ćete moći spavati u miru i tišini iako se u okolici nalazi nekoliko kafića, pubova, klubova i restorana, što znači da nećete morati ići daleko za dobar provod": "There are no permanent residents within the building, so you will be able to sleep in peace and quiet even though there are several bars, pubs, clubs and restaurants, which means you won't have to travel far for a good time ",
  "ZAJEDNIČKI PROSTOR": "COMMUNAL SPACE",
  "Kuhinja, blagavaonica i dnevni boravak su spojeni": "The kitchen, dining room and living room are joined",
  "Cijeli prostor je klimatiziran": "The entire space is air-conditioned",
  "Kuhinja je opremljena perilicom posuđa, posuđem, mikrovalnom pećnicom, pećnicom, električnim štednjakom, hladnjakom (zamrzivač i ledomat ) i aparatom za kavu": "The kitchen is equipped with a dish washer, dishes, a microwave, an oven, an electric stove, a fridge (freezer and ice machine) and a coffee machine",
  "U dnevnom boravku se nalazi TV koji ima satelitski program": "There is a TV in the living room that has a sattelite dish",
  "Jedna kupaonica je opremljena tuš kabinom, a druga kadom": "One of the bathrooms is equipped with a shower, and the other with a bath",
  "Gostima je na raspolaganju usisavač, glačalo, sušilo za kosu, ručnici, posteljina, sapun za ruke te gel za tuširanje i šampon": "Guest will have a vacuum cleaner, an iron, a hair drier, towels, bed sheets, soap, shower gel and shampoo at their disposal",
  "U cijelom apartmanu je dostupan WI-FI": "WI-FI is available throughout the whole apartment",
  "ZELENA SOBA": "THE GREEN ROOM",
  "Bračni krevet, noćni ormarići, ormar": "A double bed, bedside tables, a closet",
  "Prostor je klimatiziran": "The space is air-condicioned",
  "PLAVA SOBA": "THE BLUE ROOM",
  "2 kreveta za jednu osobu, noćni ormarići, 2 fotelje, ormar": "2 single beds, bedside tables, 2 armchairs, a closet",
  "CRVENA SOBA": "THE RED ROOM",
  "SPORTSKI SADRŽAJI": "SPORTS CONTENTS",
  "ZABAVA I ŠOPING": "SHOPPING AND ENTERTAINMENT",
  "PRIJEVOZ": "TRANSPORT",
  "ZNAMENITOSTI": "LANDMARKS",
  "KULTURNO-OBRAZOVNE USTANOVE": "CULTURAL AND EDUCATIONAL INSTITUTIONS",
  "Stadion": "Stadium",
  "Dvorana": "Sports hall",
  "Gradski Bazeni": "City pool",
  "Sportska dvorana Zrinjevac": "Sports hall Zrinjevac",
  "Sokolski Dom": "Sokolski Dom sports hall",
  "Zračna luka Osijek": "Osijek Airport",
  "ZABAVA I ŠOPING": "SHOPPING AND ENTERTAINMENT",
  "Kino": "Cinema",
  "Šoping centar": "Mall",
  "Pub": "Pub",
  "Kafić": "Bar",
  "Restoran": "Restaurant",
  "Slastičarna": "Pastry shop",
  "Mjenjačnica": "Exchange office",
  "Tržnica": "Farmer's Market",
  "Vinska mušica": "Vinska mušica vinery",
  "Pivnica": "Ale house",
  "PRIJEVOZ": "TRANSPORT",
  "Tramvaj": "tram",
  "Autobus": "bus",
  "Autobusni kolodvor": "Bus station",
  "Željeznički kolodvor": "Train station",
  "Zračna luka": "Airport",
  "ZNAMENITOSTI": "LANDMARKS",
  "Trg Ante Starčevića": "Ante Starčević square",
  "Konkatedrala Svetog Petra i Pavla apostola": "Saint Peter and Paul Concathedral",
  "Promenada": "the Promenade",
  "Tvrđa": "Tvrđa old town",
  "KULTURNO-OBRAZOVNE USTANOVE": "CULTURAL AND EDUCATIONAL INSTITUTIONS",
  "Hrvatsko Narodno kazalište": "Croatian National Theatre",
  "Gradska i Sveučilišna knjižnica": "City and University Library",
  "Muzej Slavonije": "Museum of Slavonia",
  "Hrvatska Gospodarska Komora": "The Chamber of Commerce",
  "Ekonomski fakultet": "University of Economics",
  "Filozofski fakultet": "University of Humanities",
  "Gimnazija Gaudeamus": "Gaudeamus Grammar School",
  "Odjel za matematiku sveučilišta J.J. Strossmayera": "The Department of Mathematics of the University of J.J. Strossmayer",
  "Fakultet Elektrotehnike, računarstva i informacijskih tehnologija Osijek": "Faculty of Electrical Engineering, University of Osijek",
  "Studenski centar": "The Student Centre",
  "Dolazak od": "Arrival from",
  "Odlazak od": "Departure from",
  "do": "to",
  "Pušenje u apartmanu nije dopušteno ( prostor za pušenje je ostakljena terasa )": "Smoking in the apartment is prohibited ( the smoking area is the glass terrace )",
  "Nije prikladno za kućne ljubimce": "Not appropriate for pets",
  "Dječji krevetić dostupan na upit": "Children's bed available per enquiry",
  "Transfer od zračne luke na upit": "Transport from the Airport per enquiry",
  "Parking dostupan u obližnjoj podzemnoj garaži": "Parking available at nearby parking garage",
  "GALERIJA": "GALLERY",
  "CIJENE": "PRICES",
  "osobe": "persons",
  "osoba": "person",
  "Boravišna pristojba uključena": "residence fee included",
  "Plaćanje posredstvom Booking.com": "Payment via Booking.com",
  "Plaćanje gotovinom": "Cash payment",
  "Plaćanje uplatom na račun (moguć R1)": "Payment on account (R1 possible)",
  "KONTAKT": "CONTACT",
  "Bračni krevet, noćni ormarići, fotelja i tabure": "A double bed, bedside tables, armchair, a tabouret",
  "2 kreveta za jednu osobu, noćni ormarići, fotelja i tabure": "2 single beds, bedside tables, armchair, a tabouret",
  "Sportska zračna luka": "Sport Airport",
  "Početna": "Home",
  "O Nama": "About Us",
  "Sadržaji": "Contents",
  "Apartman": "Apartment",
  "Napomena": "Remark",
  "Galerija": "Gallery",
  "Cijene": "Prices",
  "kat": "floor"
};

// Create VueI18n instance with options
const i18n = new VueI18n({
  locale: localStorage.getItem('locale') || 'hr',
  messages: {
    en
  }
})

var app = new Vue({
  i18n,
  el: '#app',
  data: {
    locale: localStorage.getItem('locale') || 'hr'
  },
  methods: {
    changeLocale(locale) {
      this.$i18n.locale = locale;
      this.locale = locale;
      localStorage.setItem('locale', locale);
    }
  }
})
